config/routes.rb
Rails.application.routes.draw do
  get 'ephemeral_remixes/index'
  get 'ephemeral_remixes/new'
  get 'ephemeral_remixes/create'
  get 'ephemeral_remixes/show'
  get 'ephemeral_remixes/destroy'
  get 'potential_users/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  authenticated :user do
    root to: 'posts#index', as: :authenticated_root
  end

  root to: "pages#home"

  resources :categories do
    collection do
      get :set_post
    end
  end

  resources :posts, param: :token, path: 'p', as: :posts do
    resources :comments, only: [:index, :show, :new, :create, :destroy]
    member do
      get 'speech', to: 'posts#speech', defaults: { format: 'mp3' }
    end
    collection do
      get :following
    end
  end

  resources :comments do
    resources :comment_replies, only: [:create, :destroy]
  end

  resources :comment_likes, only: [:create, :destroy]
  resources :comment_dislikes, only: [:create, :destroy]
  resources :comment_reply_likes, only: [:create, :destroy]
  resources :post_likes, only: [:create, :destroy]
  resources :post_qualities, only: [:create, :destroy]
  resources :saved_for_laters, only: [:index, :create, :destroy]
  resources :potential_users, only: [:create]
  resources :ephemeral_remixes, only: [:index, :new, :create, :destroy]


  resources :remixes, only: [:new, :create, :index, :show, :destroy] do
    member do
      get :audio
    end
  end

  resources :followers do
    member do
      post 'follow'
      post 'unfollow'
    end
    collection do
      get 'suggested'
    end
  end

  get "voice_design", to: "pages#voice_design"
  get "dashboard/show", to: "dashboard#show"
  get "dashboard/saved", to: "dashboard#saved"
  get '/@:nickname', to: 'profiles#show', as: 'profile'
  post '/checkout', to: 'checkout#create', as: 'checkout'
  get '/checkout/success', to: 'checkout#success', as: 'checkout_success'
  get '/checkout/cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  post '/stripe_webhooks/receive', to: 'stripe_webhooks#receive', as: 'stripe_webhooks'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_after_action :verify_authorized,  only: %i[show saved]

  def show
    @posts = current_user.posts
  end

  def saved
    @saved_posts = current_user.saved_posts.includes(:post)
  end
end

app/views/dashboard/saved.html.erb
<div class="post" >
  <!--search-bar-->
  <%= render partial: "shared/search_bar" %>
  <!--title-->
  <h4 style="color: white; margin-top: 30px;">Bookmarks</h4>
  <div class="cards mt-5">
    <div class="cards">
      <% current_user.saved_posts.each do |post| %>
        <%= link_to post_path(post.token)  do %>
          <!--cards-->
          <%= render partial: "posts/card", locals: { post: post }%>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/show.html.erb
<div class="post" >
  <!--search-bar-->
  <%= render partial: "shared/search_bar" %>
  <!--title-->
  <div class="profile" style="color:white;">
    <div class="mb-2" style="margin-top: 30px">
      <%= link_to "#profileImageModal", "data-bs-toggle" => "modal", "data-bs-target" => "#profileImageModal" do %>
        <%= image_tag url_for(current_user.photo), class: "avatar-large", loading: "lazy" %>
      <% end %>
    </div>
    <h2 class="mb-5"><%= current_user.nickname %></h2>
    <div class="d-flex justify-content-center" style="color:white;">
      <h6 class="mb-5", style="margin-right: 30px"><%= current_user.posts.count %> Posts</h6>
      <h6 class="mb-5">
        <%= link_to "#{current_user.followers_count} Followers", "#followersModal", "data-bs-toggle" => "modal", "data-bs-target" => "#followersModal" %>
      </h6>
      <h6 class="mb-5", style="margin-left: 30px">
        <%= link_to "#{current_user.follow_count} Following", "#followingModal", "data-bs-toggle" => "modal", "data-bs-target" => "#followingModal" %>
      </h6>
    </div>
    <div class="cards">
      <% @posts.order(created_at: :desc).each do |post| %>
          <!--three dots icon-->
          <div class="dropdown dropdown-post">
            <% if current_user == post.user %>
            <i class="fas fa-ellipsis-h" style="float: right; color: white;" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false"></i>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <li><%= link_to 'Delete', post_path(post.token), data: { turbo_method: :delete, turbo_confirm: 'Delete this post?' }, class: 'dropdown-item' %></li>
            </ul>
            <% end %>
          </div>
        <%= link_to post_path(post.token) do %>
          <%= render partial: "posts/card", locals: { post: post }%>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<!-- Followers Modal -->
<div class="modal fade" id="followersModal" tabindex="-1" aria-labelledby="followersModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="followersModalLabel">Followers</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <% current_user.followers_by_type('User').each do |follower| %>
          <div class="d-flex justify-content-between">
              <!--avatar-->
              <%= link_to profile_path(follower.nickname) do %>
                <div class="d-flex" style="gap:8px;">
                  <%= image_tag url_for(follower.photo), class: "avatar-xxs", loading: "lazy" %>
                  <div data-audio-target="nickname" style="color:white;font-weight:bold !important"><%= follower.nickname %></div>
                  <div data-audio-target="nickname" style="color:grey;font-weight:lighter !important">@<%= follower.nickname %></div>
                </div>
              <% end %>
            <!--follow button-->
            <div>
              <% if user_signed_in? %>
                <% user_follow = current_user.following?(follower) %>
                <% if user_follow %>
                  <%= button_to "Following ✔", unfollow_follower_path(follower), class: "btn btn-mini-following", method: :post %>
                <% else %>
                  <%= button_to "Follow back", follow_follower_path(follower), class: "btn btn-mini-follow", method: :post %>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Following Modal -->
<div class="modal fade" id="followingModal" tabindex="-1" aria-labelledby="followingModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="followingModalLabel">Following</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <% current_user.all_following.each do |followed_user| %>
          <div class="d-flex justify-content-between">
            <%= link_to profile_path(followed_user.nickname) do %>
              <div class="d-flex" style="gap:8px;">
                <!--avatar-->
                <%= image_tag url_for(followed_user.photo), class: "avatar-xxs", loading: "lazy" %>
                <!--nickname-->
                <div data-audio-target="nickname" style="color:white;font-weight:bold !important"><%= followed_user.nickname %></div>
                <div data-audio-target="nickname" style="color:grey;font-weight:lighter !important">@<%= followed_user.nickname %></div>
              </div>
            <% end %>
            <!--remove button-->
            <div>
              <% if user_signed_in? %>
                <% user_follow = current_user.following?(followed_user) %>
                <% if user_follow %>
                  <%= button_to "Remove", unfollow_follower_path(followed_user), class: "btn btn-mini-following", method: :post %>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Profile Image Modal -->
<div class="modal fade" id="profileImageModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content bg-transparent border-0">
      <div class="modal-body d-flex align-items-center justify-content-center p-0">
          <%= image_tag url_for(current_user.photo), loading: "lazy" %>
      </div>
    </div>
  </div>
</div>