config/routes.rb
Rails.application.routes.draw do
  get 'ephemeral_remixes/index'
  get 'ephemeral_remixes/new'
  get 'ephemeral_remixes/create'
  get 'ephemeral_remixes/show'
  get 'ephemeral_remixes/destroy'
  get 'potential_users/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  authenticated :user do
    root to: 'posts#index', as: :authenticated_root
  end

  root to: "pages#home"

  resources :categories do
    collection do
      get :set_post
    end
  end

  resources :posts, param: :token, path: 'p', as: :posts do
    resources :comments, only: [:index, :show, :new, :create, :destroy]
    member do
      get 'speech', to: 'posts#speech', defaults: { format: 'mp3' }
    end
    collection do
      get :following
    end
  end

  resources :comments do
    resources :comment_replies, only: [:create, :destroy]
  end

  resources :comment_likes, only: [:create, :destroy]
  resources :comment_dislikes, only: [:create, :destroy]
  resources :comment_reply_likes, only: [:create, :destroy]
  resources :post_likes, only: [:create, :destroy]
  resources :post_qualities, only: [:create, :destroy]
  resources :saved_for_laters, only: [:index, :create, :destroy]
  resources :potential_users, only: [:create]
  resources :ephemeral_remixes, only: [:index, :new, :create, :destroy]


  resources :remixes, only: [:new, :create, :index, :show, :destroy] do
    member do
      get :audio
    end
  end

  resources :followers do
    member do
      post 'follow'
      post 'unfollow'
    end
    collection do
      get 'suggested'
    end
  end

  get "voice_design", to: "pages#voice_design"
  get "dashboard/show", to: "dashboard#show"
  get "dashboard/saved", to: "dashboard#saved"
  get '/@:nickname', to: 'profiles#show', as: 'profile'
  post '/checkout', to: 'checkout#create', as: 'checkout'
  get '/checkout/success', to: 'checkout#success', as: 'checkout_success'
  get '/checkout/cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  post '/stripe_webhooks/receive', to: 'stripe_webhooks#receive', as: 'stripe_webhooks'

end

app/models/saved_for_later.rb
class SavedForLater < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }

end

app/controllers/saved_for_laters_controller.rb
class SavedForLatersController < ApplicationController
  skip_after_action :verify_authorized

  def index
    @saved_posts = current_user.saved_posts.includes(:post)
  end

  def create
    @saved_for_later = current_user.saved_for_laters.new(saved_for_later_params)
    @post = Post.find_by(id: @saved_for_later.post_id)
    if @saved_for_later.save
      render :create
    else
      flash.now[:alert] = "You already saved this post for later"
      render turbo_stream: turbo_stream.replace(@post, partial: "posts/post", locals: { post: @post })
    end
  end

  def destroy
    @saved_for_later = current_user.saved_for_laters.find(params[:id])
    @post = @saved_for_later.post
    @saved_for_later.destroy
    render :destroy
  end

  private

  def saved_for_later_params
    params.require(:saved_for_later).permit(:post_id)
  end
end

app/views/saved_for_laters/create.html.erb
<turbo-frame id="save_button_<%= @post.id %>">
  <%= button_to saved_for_later_path(@saved_for_later), class: "icon-button", method: :delete do %>
    <div class="show-icons-item" style="gap:4px;" >
      <i class="fas fa-bookmark"></i>
      <div class='icon-button' style="font-size:16px"><%= @post.saved_for_laters.count %></div>
    </div>
  <% end %>
</turbo-frame>

app/views/saved_for_laters/destroy.html.erb
<turbo-frame id="save_button_<%= @post.id %>">
  <%= button_to saved_for_laters_path, class: "icon-button", params: { saved_for_later: { post_id: @post.id }}, method: :post do %>
    <div class="show-icons-item" style="gap:4px;" >
      <i class="far fa-bookmark"></i>
      <div class='icon-button' style="font-size:16px"><%= @post.saved_for_laters.count %></div>
    </div>
  <% end %>
</turbo-frame>

app/views/saved_for_laters/index.html.erb
<h1>SavedForLaters#index</h1>
<p>Find me in app/views/saved_for_laters/index.html.erb</p>

app/views/saved_for_laters/params.html.erb
<h1>SavedForLaters#params</h1>
<p>Find me in app/views/saved_for_laters/params.html.erb</p>