config/routes.rb
Rails.application.routes.draw do
  get 'ephemeral_remixes/index'
  get 'ephemeral_remixes/new'
  get 'ephemeral_remixes/create'
  get 'ephemeral_remixes/show'
  get 'ephemeral_remixes/destroy'
  get 'potential_users/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  authenticated :user do
    root to: 'posts#index', as: :authenticated_root
  end

  root to: "pages#home"

  resources :categories do
    collection do
      get :set_post
    end
  end

  resources :posts, param: :token, path: 'p', as: :posts do
    resources :comments, only: [:index, :show, :new, :create, :destroy]
    member do
      get 'speech', to: 'posts#speech', defaults: { format: 'mp3' }
    end
    collection do
      get :following
    end
  end

  resources :comments do
    resources :comment_replies, only: [:create, :destroy]
  end

  resources :comment_likes, only: [:create, :destroy]
  resources :comment_dislikes, only: [:create, :destroy]
  resources :comment_reply_likes, only: [:create, :destroy]
  resources :post_likes, only: [:create, :destroy]
  resources :post_qualities, only: [:create, :destroy]
  resources :saved_for_laters, only: [:index, :create, :destroy]
  resources :potential_users, only: [:create]
  resources :ephemeral_remixes, only: [:index, :new, :create, :destroy]


  resources :remixes, only: [:new, :create, :index, :show, :destroy] do
    member do
      get :audio
    end
  end

  resources :followers do
    member do
      post 'follow'
      post 'unfollow'
    end
    collection do
      get 'suggested'
    end
  end

  get "voice_design", to: "pages#voice_design"
  get "dashboard/show", to: "dashboard#show"
  get "dashboard/saved", to: "dashboard#saved"
  get '/@:nickname', to: 'profiles#show', as: 'profile'
  post '/checkout', to: 'checkout#create', as: 'checkout'
  get '/checkout/success', to: 'checkout#success', as: 'checkout_success'
  get '/checkout/cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  post '/stripe_webhooks/receive', to: 'stripe_webhooks#receive', as: 'stripe_webhooks'

end

app/views/shared/_envelop.html.erb
<svg width="36" height="32" viewBox="0 0 18 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M16.8438 5.9765L9.34378 0.976501C9.24103 0.911165 9.12179 0.876465 9.00003 0.876465C8.87827 0.876465 8.75903 0.911165 8.65628 0.976501L1.15628 5.9765C1.06914 6.03303 0.997675 6.11065 0.948511 6.20214C0.899348 6.29364 0.874072 6.39607 0.875026 6.49994V14.6249C0.875026 14.9565 1.00672 15.2744 1.24114 15.5088C1.47556 15.7432 1.79351 15.8749 2.12503 15.8749H15.875C16.2065 15.8749 16.5245 15.7432 16.7589 15.5088C16.9933 15.2744 17.125 14.9565 17.125 14.6249V6.49994C17.126 6.39607 17.1007 6.29364 17.0515 6.20214C17.0024 6.11065 16.9309 6.03303 16.8438 5.9765ZM9.00003 2.24994L15.3985 6.51556L10.1641 10.2499H7.83596L2.60159 6.51556L9.00003 2.24994ZM2.12503 14.6249V7.71088L7.27346 11.3828C7.37805 11.4584 7.50374 11.4994 7.63284 11.4999H10.3672C10.4963 11.4994 10.622 11.4584 10.7266 11.3828L15.875 7.71088V14.6249H2.12503Z" fill="white"/>
</svg>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar-expand" data-controller="navbar">
  <div class="navbar-left">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto" style="width: 100%">
        <% if user_signed_in? %>
          <div class= "navbar-items">
            <li class="nav-logo">
              <%= link_to "/", class: "navbar-brand" do %>
                <%= image_tag "yoinity_logo.png" %>
              <% end %>
              <div class="all-text-white", style="font-size: 24px">
                <%= link_to "Yoinity", "/", class: "yoinity-logo"%>
              </div>
            </li>
            <li class="nav-item">
              <h6>
                <%= link_to raw("<span class='icon'><i class='fas fa-home'></i></span><span>Home</span>"), "/", class: "navbar-link tab-index", data: { navbar_target: 'link' } %>
              </h6>
            </li>
            <% unless current_user.subscription_status == 'active' %>
              <li class="nav-item">
                <h6>
                  <%= link_to raw("<span class='icon'><i class='fas fa-crown'></i></span><span>Membership</span>"), "#", id: "checkout-button", data: { controller: "checkout", action: "click->checkout#checkout" }, class: "navbar-link tab-index" %>
                </h6>
              </li>
            <% end %>
            <li class="nav-item">
              <h6>
                <%= link_to raw("<span class='icon'><i class='fas fa-bookmark'></i></span><span>Bookmarks</span>"), "/dashboard/saved", class: "navbar-link tab-index", data: { navbar_target: 'link' } %>
              </h6>
            </li>
            <li class="nav-item">
              <h6>
                <%= link_to raw("<span class='icon'><i class='fas fa-compact-disc'></i></span><span>Remixes</span>"), "/remixes", class: "navbar-link tab-index", data: { navbar_target: 'link' } %>
              </h6>
            </li>
            <li class="nav-item">
              <h6>
                <%= link_to raw("<span class='icon'><i class='fas fa-user'></i></span><span>Profile</span>"), "/dashboard/show", class: "navbar-link tab-index", data: { navbar_target: 'link' } %>
              </h6>
            </li>
            <li class="mt-5 mb-5">
              <%= link_to "Voice design", "/voice_design", class: "yoinity-logo navbar-link tab-index", data: { navbar_target: 'link' } %>
            </li>
            <!--create button-->
            <% if action_name == "index" && controller_name == "posts" %>
              <li class="nav-item">
                <%= link_to "Create", "#remixModal", "data-bs-toggle" => "modal", "data-bs-target" => "#remixModal", class: "btn btn-create" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Create", "/remixes/new", class: "btn btn-create" %>
              </li>
            <% end %>
            <!--account-menu-->
            <div class="account-menu">
              <!--avatar profile-->
              <%= image_tag url_for(current_user.photo), class: "avatar-navbar dropdown-toggle", role: "button",  id: "dropdownMenuLink", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
              <!--nickname-->
              <div class="align-items-center" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                <div style="color:white;font-size:14px" ><%= current_user.nickname %></div>
                <div style="color:grey;font-size:14px" >@<%= current_user.nickname %></div>
              </div>
              <i class="fas fa-ellipsis-h" style="float: right; color: white;margin-left:26px" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
            </div>
          </div>
        <% else %>
          <div class= "navbar-items">
            <li class="nav-logo">
              <%= link_to "/", class: "navbar-brand" do %>
                <%= image_tag "yoinity_logo.png" %>
              <% end %>
              <div class="all-text-white", style="font-size: 24px">
                <%= link_to "Yoinity", "/", class: "yoinity-logo"%>
              </div>
            </li>
            <li class="nav-item all-text-grey">
              <%= link_to "Login", new_user_session_path, class: "navbar-link tab-index" %>
            </li>
            <li class="nav-item mt-5">
              <%= link_to "Sign up", new_user_registration_path, class: "btn btn-create" %>
            </li>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_right.erb
<div class="navbar-expand">
  <div class="navbar-right">
    <div class="d-flex">
      <p class="all-text-white", style="font-size: 18px">
        <%= link_to "Who to follow", "/", class: "yoinity-logo"%>
      </p>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto" style="width: 100%">
          <div class= "">
            <li class="">
                  <% @users.each do |user| %>
                    <div class="d-flex justify-content-between" style='gap:8px'>
                      <!--avatar profile-->
                      <%= link_to profile_path(user.nickname) do %>
                      <div class="d-flex">
                        <%= image_tag url_for(user.photo), class: "avatar-navbar" %>
                        <!--nickname-->
                        <div class="align-items-center">
                          <div style="color:white;font-size:14px" ><%= user.nickname %></div>
                          <div style="color:grey;font-size:14px" >@<%= user.nickname %></div>
                        </div>
                      </div>
                      <% end %>
                      <turbo-frame id="follow_button_<%= user.id %>">
                        <% user_follow = current_user.following?(user) %>
                        <% if user_follow %>
                          <h2 class = "d-flex align-items-center"><%= button_to "Following ✔", unfollow_follower_path(user), class: "btn btn-mini-following", method: :post, remote: true %></h2>
                        <% else %>
                          <h2 class = "d-flex align-items-center"><%= button_to "Follow", follow_follower_path(user), class: "btn btn-mini-follow", method: :post, remote: true %></h2>
                        <% end %>
                      </turbo-frame>
                    </div>
                  <% end %>
            </li>
          </div>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_play_icon.html.erb
<div class="avatar-xxs index-play-button" style="border-radius:50%; display: flex; justify-content: center; align-items: center;">
  <i class="fas fa-play" style="color: white"></i>
</div>

app/views/shared/_search_bar.html.erb
<div class="search-form-control form-group">
  <%= simple_form_for :search, url: posts_path, method: :get, html:{class: 'search-bar'} do |f|  %>
    <input placeholder="Search any topic" class="form-control string required" type="text" name="query" id="search_query"/>
  <% end %>
</div>