config/routes.rb
Rails.application.routes.draw do
  get 'ephemeral_remixes/index'
  get 'ephemeral_remixes/new'
  get 'ephemeral_remixes/create'
  get 'ephemeral_remixes/show'
  get 'ephemeral_remixes/destroy'
  get 'potential_users/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  authenticated :user do
    root to: 'posts#index', as: :authenticated_root
  end

  root to: "pages#home"

  resources :categories do
    collection do
      get :set_post
    end
  end

  resources :posts, param: :token, path: 'p', as: :posts do
    resources :comments, only: [:index, :show, :new, :create, :destroy]
    member do
      get 'speech', to: 'posts#speech', defaults: { format: 'mp3' }
    end
    collection do
      get :following
    end
  end

  resources :comments do
    resources :comment_replies, only: [:create, :destroy]
  end

  resources :comment_likes, only: [:create, :destroy]
  resources :comment_dislikes, only: [:create, :destroy]
  resources :comment_reply_likes, only: [:create, :destroy]
  resources :post_likes, only: [:create, :destroy]
  resources :post_qualities, only: [:create, :destroy]
  resources :saved_for_laters, only: [:index, :create, :destroy]
  resources :potential_users, only: [:create]
  resources :ephemeral_remixes, only: [:index, :new, :create, :destroy]


  resources :remixes, only: [:new, :create, :index, :show, :destroy] do
    member do
      get :audio
    end
  end

  resources :followers do
    member do
      post 'follow'
      post 'unfollow'
    end
    collection do
      get 'suggested'
    end
  end

  get "voice_design", to: "pages#voice_design"
  get "dashboard/show", to: "dashboard#show"
  get "dashboard/saved", to: "dashboard#saved"
  get '/@:nickname', to: 'profiles#show', as: 'profile'
  post '/checkout', to: 'checkout#create', as: 'checkout'
  get '/checkout/success', to: 'checkout#success', as: 'checkout_success'
  get '/checkout/cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  post '/stripe_webhooks/receive', to: 'stripe_webhooks#receive', as: 'stripe_webhooks'

end

app/models/post_like.rb
class PostLike < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/controllers/post_likes_controller.rb
class PostLikesController < ApplicationController
  skip_after_action :verify_authorized

  def create
    @post_like = current_user.post_likes.new(post_like_params)
    @post = Post.find_by(id: @post_like.post_id)
    if @post_like.save
      render :create
    else
      flash.now[:alert] = "You already liked this post"
      render turbo_stream: turbo_stream.replace(@post, partial: "posts/post", locals: { post: @post })
    end
  end

  def destroy
    @post_like = current_user.post_likes.find(params[:id])
    @post = @post_like.post
    @post_like.destroy
    render :destroy
  end

  def post_like_params
    params.require(:post_like).permit(:post_id)
  end
end

app/views/post_likes/create.html.erb
<!-- app/views/post_likes/create.html.erb -->
<turbo-frame id="like_button_<%= @post.id %>">
  <%= button_to post_like_path(@post_like), class: "icon-button", method: :delete do %>
    <div class="show-icons-item"  style="gap:4px;">
      <div><i class="fas fa-heart" style="color: #FF3040"></i></div>
      <div class='icon-button' style="font-size:16px"><%= @post.post_likes.count %></div>
    </div>
  <% end %>
</turbo-frame>

app/views/post_likes/destroy.html.erb
<!-- app/views/post_likes/destroy.html.erb -->
<turbo-frame id="like_button_<%= @post.id %>">
  <%= button_to post_likes_path, class: "icon-button", params: { post_like: { post_id: @post.id }}, method: :post do %>
    <div class="show-icons-item" style="gap:4px;">
      <div><i class="far fa-heart"></i></div>
      <div class='icon-button' style="font-size:16px"><%= @post.post_likes.count %></div>
    </div>
  <% end %>
</turbo-frame>

app/views/post_likes/post_like_params.html.erb
<h1>PostLikes#post_like_params</h1>
<p>Find me in app/views/post_likes/post_like_params.html.erb</p>